[package_management]
manager = "uv"

[keymap]
preset = "default"
[keymap.overrides]

[completion]
activate_on_typing = true
copilot = false

[runtime]
default_sql_output = "auto"
on_cell_change = "autorun"
reactive_tests = true
watcher_on_save = "lazy"
auto_instantiate = true
auto_reload = "autorun"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000

[formatting]
line_length = 79

[diagnostics]
enabled = false

[language_servers.pylsp]
enable_mypy = true
enable_pylint = false
enable_pydocstyle = false
enabled = true
enable_pyflakes = false
enable_flake8 = false
enable_ruff = true

[server]
follow_symlink = false
browser = "default"

[display]
default_width = "medium"
default_table_page_size = 10
theme = "light"
code_editor_font_size = 14
cell_output = "above"
dataframes = "rich"

[ai]
rules = ""
[ai.open_ai]

[ai.anthropic]

[ai.google]

[snippets]
include_default_snippets = true
custom_paths = []

[save]
format_on_save = false
autosave_delay = 1000
autosave = "after_delay"
