# T3 Foundation Gemstone Project [t3gemstone.org]
# SPDX-License-Identifier: Apache-2.0

version: '3'

vars:
  MACHINE: '{{ .MACHINE | default "t3-gem-o1" }}'
  BUILDDIR: '{{ .ROOT_DIR }}/build'
  DOWNLOAD_DIR: '{{.BUILDDIR}}/downloads'
  TOOLCHAIN_DIR: '{{.BUILDDIR}}/toolchain'
  TI_INSTALL_DIR: '{{.TOOLCHAIN_DIR}}/ti'
  TOOLCHAIN_URL: 'https://github.com/t3gemstone/toolchains/archive/refs/tags/prebuilt-toolchain-ubuntu-jammy-1.0.1.tar.xz'

env:
  TI_SDK_PATH: '{{ .TI_INSTALL_DIR }}/ti-processor-sdk-rtos-j722s-evm-10_01_00_04'

tasks:

  default:
    silent: true
    cmds:
      - task --list-all --summary
      - echo
      - echo "Environment:"
      - echo
      - echo "  MACHINE         = '{{ .MACHINE }}'"
      - echo "  BUILDDIR        = '{{ .BUILDDIR }}'"
      - echo "  DOWNLOAD_DIR    = '{{ .DOWNLOAD_DIR }}'"
      - echo "  TOOLCHAIN_DIR   = '{{ .TOOLCHAIN_DIR }}'"
      - echo "  TI_INSTALL_DIR  = '{{ .TI_INSTALL_DIR }}'"
      - echo "  TI_SDK_PATH     = '{{ .TI_SDK_PATH }}'"
      - echo

  destroy:
    cmds:
      - rm -rf .venv
      - rm -rf .devbox
